### ISSUE TITLE
Linux build needs to be retriggered

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/monkeytype-feedstock#1]
Seems it tried to build before `retype-feedstock` was done.

**Comment by nehaljwani** [comment]
I re-triggered the build for Linux.

https://anaconda.org/conda-forge/monkeytype/18.1.11/download/linux-64/monkeytype-18.1.11-py36_0.tar.bz2

**Comment by bollwyvl** [comment]
Much appreciated @nehaljwani!
